### ISSUE TITLE
Inconsistent function names

### ISSUE THREAD

**Issue by boathit** [one-more-minute/Lazy.jl#24]
Why use `takewhile` but `drop_while` and `take_nth`, etc., it confuses me

**Comment by one-more-minute** [comment]
A long time ago, underscores were a lot more common in Julia function names. It's since been decided that they were a bad idea, and we've changed some of the names to reflect that, though clearly some slipped through the net.

Feel free to send in a PR removing all the underscores; should be pretty easy to do ;)

**Comment by boathit** [comment]
PR has been merged.
